package ru.jleague13.calendar;

/**
 * @author ashevenkov 07.10.16 10:22.
 */
public enum EventType {

    NONE,
    REGULAR_TOUR,
    LEAGUE_CUP,
    TRAIN,
    CUP_A,
    L_CHAMP,
    CUP_F,
    T_AUCTION,
    FRIEND_GAME,
    BANKRUPCY,
    CLOSE_TRANSFER_CLAIM,
    TRANSFER_FIRST,
    CLUB_NAME_CHANGE,
    BUILDINGS,
    SCHEDULE,
    SPORT_SCHOOL_OUT,
    CHANGE,
    FA13_BUYOUT,
    SPORT_SCHOOL_BUY,
    TRANSFER_FINAL,
    WORLD_CH,
    GOLDEN,
    LAST_CHECK,
    YOUTH_WORLD_CH,
    RENT,
    SEASON_PREPARE,
    NEW_TEST,
    SEASON_START,
    COMMERCE,
    ALL_CHEMP,
    KBL, SEASON_FINISH, BLATTER
}
